/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.care.view;

import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Finishings;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import pet.care.control.GlobalValues;
import pet.care.control.LocaleBundle;
import pet.care.model.UserModel;

/**
 *
 * @author nguye
 */
public class HomeAppForm extends javax.swing.JFrame {
    private UserModel currentUser;
    /**
     * Creates new form HomeAppForm
     */
    public HomeAppForm(UserModel currentUser) {
        this.currentUser = currentUser;
        
        Locale.setDefault(LocaleBundle.getLocale());
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RegisterDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
        editComponentsMod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPet = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnMedicine = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnUser = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pet Care");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        btnPet.setBackground(new java.awt.Color(255, 51, 51));
        btnPet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPet.setForeground(new java.awt.Color(0, 153, 153));
        btnPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_pet.png"))); // NOI18N
        btnPet.setText("Quản lý thú cưng");
        btnPet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPet.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnPet.setOpaque(false);
        btnPet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetActionPerformed(evt);
            }
        });

        btnStaff.setBackground(new java.awt.Color(255, 51, 51));
        btnStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStaff.setForeground(new java.awt.Color(0, 153, 153));
        btnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_staff_manager.png"))); // NOI18N
        btnStaff.setText("Quản lý nhân viên");
        btnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaff.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnStaff.setOpaque(false);
        btnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnMedicine.setBackground(new java.awt.Color(255, 51, 51));
        btnMedicine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMedicine.setForeground(new java.awt.Color(0, 153, 153));
        btnMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_medical_suitecase.png"))); // NOI18N
        btnMedicine.setText("Quản lý thuốc");
        btnMedicine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMedicine.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnMedicine.setOpaque(false);
        btnMedicine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineActionPerformed(evt);
            }
        });

        btnMoney.setBackground(new java.awt.Color(255, 51, 51));
        btnMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoney.setForeground(new java.awt.Color(0, 153, 153));
        btnMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_money_manager.png"))); // NOI18N
        btnMoney.setText("Quản lý thu chi");
        btnMoney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoney.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnMoney.setOpaque(false);
        btnMoney.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(255, 51, 51));
        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(0, 153, 153));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_client.png"))); // NOI18N
        btnCustomer.setText("Quản lý khách hàng");
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnCustomer.setOpaque(false);
        btnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 153, 153));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setToolTipText("Thoát khỏi ứng dụng");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnExit.setOpaque(false);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 153, 153));
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_user_male_24.png"))); // NOI18N
        lblUsername.setText("Người dùng");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
        });

        btnLogout.setForeground(new java.awt.Color(0, 255, 204));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/ic_signout.png"))); // NOI18N
        btnLogout.setToolTipText("Đăng xuất");

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(23, 23, 23))
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addComponent(lblUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnMoney)
                            .addGap(18, 18, 18)
                            .addComponent(btnCustomer)
                            .addGap(18, 18, 18)
                            .addComponent(btnExit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnPet)
                            .addGap(18, 18, 18)
                            .addComponent(btnStaff)
                            .addGap(18, 18, 18)
                            .addComponent(btnMedicine))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMedicine)
                    .addComponent(btnStaff)
                    .addComponent(btnPet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addComponent(btnCustomer)
                    .addComponent(btnMoney))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetActionPerformed
        // TODO add your handling code here:
        if(!currentUser.isAdmin()){
            PetManagerForm petManagerForm = new PetManagerForm(this);
            petManagerForm.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, LocaleBundle.getResourceBundle().getString("accessdenied")
                    ,LocaleBundle.getResourceBundle().getString("error"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPetActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        if(currentUser.isAdmin()){
            StaffManagerForm staffManagerForm = new StaffManagerForm(this);
            staffManagerForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, LocaleBundle.getResourceBundle().getString("accessdenied")
                    ,LocaleBundle.getResourceBundle().getString("error"), JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineActionPerformed
        // TODO add your handling code here:
        if(currentUser.isAdmin()){
            MedicineManagerForm medicineManagerForm = new MedicineManagerForm(this);
            medicineManagerForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, LocaleBundle.getResourceBundle().getString("accessdenied")
                    ,LocaleBundle.getResourceBundle().getString("error"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMedicineActionPerformed

    private void btnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoneyActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        if(!currentUser.isAdmin()){
            CustomerManagerForm customerManagerForm = new CustomerManagerForm(this);
        } else {
            JOptionPane.showMessageDialog(this, LocaleBundle.getResourceBundle().getString("accessdenied")
                    ,LocaleBundle.getResourceBundle().getString("error"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello");
    }//GEN-LAST:event_lblUsernameMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeAppForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMedicine;
    private javax.swing.JButton btnMoney;
    private javax.swing.JButton btnPet;
    private javax.swing.JButton btnStaff;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnUser;
    // End of variables declaration//GEN-END:variables

    private void editComponentsMod() {
        lblUsername.setText(this.currentUser.getName());
        //btnPetManager1.setBorder(null);
        //btnPetManager1.setBorderPainted(false);
        pnUser.setBackground(GlobalValues.formBackgroundColor);
        btnPet.setContentAreaFilled(false);
        btnPet.requestFocus();
        btnStaff.setContentAreaFilled(false);
        btnMedicine.setContentAreaFilled(false);
        btnMoney.setContentAreaFilled(false);
        btnCustomer.setContentAreaFilled(false);
        btnExit.setContentAreaFilled(false);
        //btnPetManager1.setOpaque(false);
        
        
        if(currentUser.isAdmin()){
            //btnPet.setEnabled(false);
            //btnCustomer.setEnabled(false);
            btnPet.setForeground(GlobalValues.formDisableColor);
            btnCustomer.setForeground(GlobalValues.formDisableColor);
        }
        if(!currentUser.isAdmin()){
//            btnDrug.setEnabled(false);
//            btnMoney.setEnabled(false);
//            btnStaff.setEnabled(false);
            btnMedicine.setForeground(GlobalValues.formDisableColor);
            btnMoney.setForeground(GlobalValues.formDisableColor);
            btnStaff.setForeground(GlobalValues.formDisableColor);
        }
    }
}
