/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.care.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import pet.care.PetCare;
import pet.care.control.GlobalValues;
import pet.care.control.LocaleBundle;
import pet.care.model.UserModel;

/**
 *
 * @author nguye
 */
public class LoginDialog extends javax.swing.JFrame {
    /**
     * Creates new form LoginDialog
     */
    public LoginDialog() {
        Locale.setDefault(LocaleBundle.getLocale());
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
//        URL urlIcon;
//        urlIcon = getClass().getResource("login_favicon.ico");
//        ImageIcon imageIcon = new ImageIcon(urlIcon);
//        this.setIconImage(imageIcon.getImage());
        txtUsername.requestFocus(); 
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        chkRememberPassword = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        chkAdmin = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        lblAvatar = new javax.swing.JLabel();
        cbxLanguage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pet/care/view/Bundle"); // NOI18N
        setTitle(bundle.getString("LoginDialog.title")); // NOI18N
        setBackground(new java.awt.Color(200, 230, 201));
        setForeground(new java.awt.Color(185, 246, 202));
        setResizable(false);

        lblUsername.setBackground(new java.awt.Color(153, 255, 153));
        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 204, 153));
        lblUsername.setText(bundle.getString("LoginDialog.lblUsername.text")); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 204, 153));
        lblPassword.setText(bundle.getString("LoginDialog.lblPassword.text")); // NOI18N

        txtUsername.setToolTipText(bundle.getString("LoginDialog.txtUsername.toolTipText")); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(105, 240, 174));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(bundle.getString("LoginDialog.lblTitle.text")); // NOI18N

        chkRememberPassword.setForeground(new java.awt.Color(0, 204, 153));
        chkRememberPassword.setText(bundle.getString("LoginDialog.chkRememberPassword.text")); // NOI18N
        chkRememberPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRememberPasswordActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 204, 153));
        btnLogin.setText(bundle.getString("LoginDialog.btnLogin.text")); // NOI18N
        btnLogin.setActionCommand(bundle.getString("LoginDialog.btnLogin.actionCommand")); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        chkAdmin.setForeground(new java.awt.Color(0, 204, 153));
        chkAdmin.setText(bundle.getString("LoginDialog.chkAdmin.text")); // NOI18N

        txtPassword.setToolTipText(bundle.getString("LoginDialog.txtPassword.toolTipText")); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/user_yellow_96px.png"))); // NOI18N
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 240, 174)));

        cbxLanguage.setForeground(new java.awt.Color(0, 204, 153));
        cbxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng việt", "English" }));
        cbxLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLanguageItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(btnLogin)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(chkRememberPassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkAdmin))
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkRememberPassword)
                            .addComponent(chkAdmin)))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void chkRememberPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRememberPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRememberPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        loginAction();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbxLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLanguageItemStateChanged
        // TODO add your handling code here:
        switch(cbxLanguage.getSelectedIndex()){
            case LocaleBundle.VI:
                LocaleBundle.setLocale(LocaleBundle.VI);
                break;
            case LocaleBundle.EN:
                LocaleBundle.setLocale(LocaleBundle.EN);
                break;
        }
        /***
         * Chưa biết phải làm sao để load lại form "Login" sau khi cập nhật ngôn ngữ T_T
         */
        {
            lblTitle.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.lblTitle.text"));
            lblUsername.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.lblUsername.text"));
            lblPassword.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.lblPassword.text"));
            chkRememberPassword.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.chkRememberPassword.text"));
            chkAdmin.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.chkAdmin.text"));
            btnLogin.setText(LocaleBundle.getResourceBundle().getString("LoginDialog.btnLogin.text"));
        }
    }//GEN-LAST:event_cbxLanguageItemStateChanged

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loginAction();
        }
        
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void loginAction(){
        InputVerifier inputVerifier = new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                if(((JTextField) input).getText().equals("") || ((JTextField) input).getText().contains(" ")){
                    return false;
                } else {
                    return true;
                }
            }
        };
        if(!inputVerifier.verify(txtUsername) || !inputVerifier.verify(txtPassword)) 
        {
            JOptionPane.showMessageDialog(this, LocaleBundle.getResourceBundle().getString("LoginModel.checkinput")
                    , "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            UserModel userRequest = new UserModel(txtUsername.getText(), txtPassword.getText()
                    , chkRememberPassword.isSelected(), chkAdmin.isSelected());
            if(PetCare.requestLogin(userRequest)){
                this.dispose();
            } else {
                txtUsername.requestFocus();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbxLanguage;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JCheckBox chkRememberPassword;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
