/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet.care.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.File;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import pet.care.control.GlobalValues;
import pet.care.control.LocaleBundle;

/**
 *
 * @author nguye
 */
public class RegisterDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */
    public RegisterDialog() {
        Locale.setDefault(LocaleBundle.getLocale());
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RegisterDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
//        URL urlIcon;
//        urlIcon = getClass().getResource("login_favicon.ico");
//        ImageIcon imageIcon = new ImageIcon(urlIcon);
//        this.setIconImage(imageIcon.getImage());
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(GlobalValues.formBackgroundColor);
        Font font = lblDeal.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblDeal.setFont(font.deriveFont(attributes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dalDeal = new javax.swing.JDialog();
        lblDealDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDealDetail = new javax.swing.JTextArea();
        btnOkDeal = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        chkDeal = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        lblAvatar = new javax.swing.JLabel();
        lblPasswordReType = new javax.swing.JLabel();
        txtPasswordReType = new javax.swing.JPasswordField();
        lblDeal = new javax.swing.JLabel();

        dalDeal.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pet/care/view/Bundle"); // NOI18N
        dalDeal.setTitle(bundle.getString("RegisterDialog.dalDeal.title")); // NOI18N
        dalDeal.setBackground(new java.awt.Color(250, 250, 250));
        dalDeal.setMinimumSize(new java.awt.Dimension(575, 390));
        dalDeal.setPreferredSize(new java.awt.Dimension(575, 390));
        dalDeal.setResizable(false);
        dalDeal.setSize(new java.awt.Dimension(575, 390));

        lblDealDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDealDetail.setForeground(new java.awt.Color(0, 153, 153));
        lblDealDetail.setText(bundle.getString("RegisterDialog.lblDealDetail.text")); // NOI18N

        txtDealDetail.setEditable(false);
        txtDealDetail.setColumns(20);
        txtDealDetail.setLineWrap(true);
        txtDealDetail.setRows(5);
        txtDealDetail.setText(bundle.getString("RegisterDialog.txtDealDetail.text")); // NOI18N
        txtDealDetail.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDealDetail);

        btnOkDeal.setText(bundle.getString("RegisterDialog.btnOkDeal.text")); // NOI18N
        btnOkDeal.setActionCommand(bundle.getString("RegisterDialog.btnOkDeal.actionCommand")); // NOI18N

        javax.swing.GroupLayout dalDealLayout = new javax.swing.GroupLayout(dalDeal.getContentPane());
        dalDeal.getContentPane().setLayout(dalDealLayout);
        dalDealLayout.setHorizontalGroup(
            dalDealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dalDealLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dalDealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkDeal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(dalDealLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblDealDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dalDealLayout.setVerticalGroup(
            dalDealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dalDealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDealDetail)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkDeal)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("RegisterDialog.title")); // NOI18N
        setBackground(new java.awt.Color(200, 230, 201));
        setForeground(new java.awt.Color(185, 246, 202));

        lblUsername.setBackground(new java.awt.Color(153, 255, 153));
        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 204, 153));
        lblUsername.setText(bundle.getString("RegisterDialog.lblUsername.text")); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 204, 153));
        lblPassword.setText(bundle.getString("RegisterDialog.lblPassword.text")); // NOI18N

        txtUsername.setToolTipText(bundle.getString("RegisterDialog.txtUsername.toolTipText")); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(105, 240, 174));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(bundle.getString("RegisterDialog.lblTitle.text")); // NOI18N

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 204, 153));
        btnLogin.setText(bundle.getString("RegisterDialog.btnLogin.text")); // NOI18N
        btnLogin.setActionCommand(bundle.getString("RegisterDialog.btnLogin.actionCommand")); // NOI18N

        chkDeal.setBackground(new java.awt.Color(250, 250, 250));
        chkDeal.setForeground(new java.awt.Color(0, 204, 153));
        chkDeal.setText(bundle.getString("RegisterDialog.chkDeal.text")); // NOI18N
        chkDeal.setActionCommand(bundle.getString("RegisterDialog.chkDeal.actionCommand")); // NOI18N

        txtPassword.setToolTipText(bundle.getString("RegisterDialog.txtPassword.toolTipText")); // NOI18N

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pet/care/view/drawable/user_yellow_96px.png"))); // NOI18N
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 240, 174)));
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatarMouseClicked(evt);
            }
        });

        lblPasswordReType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPasswordReType.setForeground(new java.awt.Color(0, 204, 153));
        lblPasswordReType.setText(bundle.getString("RegisterDialog.lblPasswordReType.text")); // NOI18N

        txtPasswordReType.setText(bundle.getString("RegisterDialog.txtPasswordReType.text")); // NOI18N

        lblDeal.setForeground(new java.awt.Color(0, 204, 153));
        lblDeal.setText(bundle.getString("RegisterDialog.lblDeal.text")); // NOI18N
        lblDeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDealMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPasswordReType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPasswordReType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordReType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasswordReType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkDeal)
                            .addComponent(lblDeal))
                        .addGap(20, 20, 20)
                        .addComponent(btnLogin)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void lblAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser(GlobalValues.currentDirectory);
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()) return true;
                String fileExt = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                if(fileExt.equalsIgnoreCase("jpg") || fileExt.equalsIgnoreCase("png")){
                    return true;
                } else {
                    return false;
                }
            }
            @Override
            public String getDescription() {
                return "jpg,png";
            }
        });
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            GlobalValues.currentDirectory = chooser.getSelectedFile().getParentFile();
        }
    }//GEN-LAST:event_lblAvatarMouseClicked

    private void lblDealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDealMouseClicked
        // TODO add your handling code here:
        dalDeal.setLocationRelativeTo(null);
        dalDeal.setBackground(Color.decode("#FAFAFA"));
        dalDeal.setVisible(true);
    }//GEN-LAST:event_lblDealMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOkDeal;
    private javax.swing.JCheckBox chkDeal;
    private javax.swing.JDialog dalDeal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblDeal;
    private javax.swing.JLabel lblDealDetail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordReType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtDealDetail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordReType;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
